server:
  port: 8089

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: {client_id}
            client-secret: {client_secret}
          git-hub:
            client-id: {client_id}
            client-secret: {client_secret}
          keycloak:
            client-id: study-spring-security
            client-secret: 71514ff7-71c3-4d5d-a939-ad95bcd08950
            client-name: Key Cloak
            scope: profile, email, address
            redirect-uri: http://localhost:8089/login/oauth2/code/keycloack
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            provider: keycloak-provider
        provider:
          keycloak-provider:
            authorization-uri: http://localhost:8080/auth/realms/study/protocol/openid-connect/auth
            token-uri: http://localhost:8080/auth/realms/study/protocol/openid-connect/token
            user-info-uri: http://localhost:8080/auth/realms/study/protocol/openid-connect/userinfo
            user-name-attribute: sub


